openapi: "3.0.2"
info:
  title: "Validator Wrapper API"
  description: "Official API documentations for the Validator Wrapper."
  version: ""
  contact:
    name: "Validator Wrapper"
    url: "https://validator.fhir.org/"
servers:
  - url: "https://validator.fhir.org/"

paths:
  /validate:
    post:
      tags:
        - Validate a Resource
      description: "Validates resources and returns the validation results."
      operationId: ValidateAResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/validationRequest"

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validateResponse"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                title: validateBadRequest
                type: string
                example: "No files for validation provided in request."
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                title: validateInternalServerError
                type: string
                example: "Internal server error."
  /validator/version:
    get:
      tags:
        - List Validator Version
      description: "Returns the current validator version."
      operationId: ListValidatorVersion
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                title: validatorVersionOK
                type: string
                example: "5.6.39"
  /convert:
    post:
      tags:
        - Convert a Resource
      description: "Converts a resource."
      operationId: ConvertAResource
      produces:
        - application/json
        - application/xml
        - application/fhir+json
        - application/fhir+xml
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
          application/fhir+json:
            schema:
              type: object
          application/xml:
            schema:
              type: object
          application/fhir+xml:
            schema:
              type: object
      parameters:
        - in: query
          name: type
          schema:
            type: string
          description: xml or json
        - in: query
          name: toType
          schema:
            type: string
          description: xml or json
        - in: query
          name: version
          schema:
            type: string
          description: source FHIR version (takes precedence over fhirVersion parameter of Content-Type header)
        - in: query
          name: toVersion
          schema:
            type: string
          description: target FHIR version (takes precedence over fhirVersion parameter of Accept header)
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                title: convertBadRequest
                type: string
                example: "Invalid toType parameter! Supported xml or json."
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                title: convertInternalServerError
                type: string
                example: "Internal server error."
  /ig:
    get:
      tags:
        - List IGs
      description: "Returns the list of available implementation guides."
      operationId: ListIgs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listIgsResponse"
        "500":
          description: "Internal Server Error."
          content:
            text/plain:
              schema:
                title: igInternalServerError
                type: string
                example: "No IGs returned from igController. List size is 0."
  /igVersions/{igPackageName}:
    get:
      tags:
        - List IG Versions
      description: "Returns the list of available versions for a specific implementation guide. (specified through parameter <igPackageName>)"
      operationId: ListIgVersions
      parameters:
        - in: path
          name: igPackageName
          required: true
          description: "Implementation guide package name"
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listIgVersionsResponse"
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                title: igVersionsInternalServerError
                type: string
                example: "No IGs returned from igController. List size is 0."
  /versions:
    get:
      tags:
        - List Supported FHIR Versions
      description: "Returns the list of supported FHIR versions."
      operationId: ListSupportedFhirVersions
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listSupportedFhirVersions"
        "500":
          description: "Internal Server Error."
          content:
            text/plain:
              schema:
                title: fhirVersionsInternalServerError
                type: string
                example: "Empty fhir version list returned from core libraries."
  /terminology:
    post:
      tags:
        - Validate Terminology Server
      description: "Returns the validation result of the given terminology server."
      operationId: ValidateTerminologyServer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/validateTerminologyServerRequest"

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validateTerminologyServerResponse"
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                title: terminologyInternalServerError
                type: string
                example: Internal server error.

  /txStatus:
    get:
      tags:
        - Terminology Server Status
      description: "Returns the status of the terminology server in boolean."
      operationId: terminologyServerStatus
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/terminologyServerStatus"
  /packStatus:
    get:
      tags:
        - Package Server Status
      description: "Returns the status of the package server in boolean."
      operationId: packageServerStatus
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/packageServerStatus"


components:
  parameters:
  schemas:
    validationRequest:
      type: object
      properties:
        cliContext:
          type: object
          properties:
            extensions:
              type: array
              items:
                type: string
              description: "A list of urls for domains from which extensions will be allowed. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Extensions)"
            doNative:
              type: boolean
              description: "Validates against non-FHIR xml, json and RDF schemas. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-NativeValidation)"
            hintAboutNonMustSupport:
              type: boolean
              description: "Flags instances where data elements are present that are not \"mustSupport\" in profiles. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-MustSupport)"
            assumeValidRestReferences:
              type: boolean
              description: "Instructs the validator to use the type found in references that look like valid RESTful URLs when validating the type of the reference. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-assumeValidRestReferences)"
            noExtensibleBindingMessages:
              type: boolean
              description: "Turns off warnings produced when the validator encounters a code that is not part of an extensible binding. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Extensiblebindingwarnings)"
            showTimes:
              type: boolean
              description: "Produces logging summarizing how long some internal processes took. *This will only be visible in server logs, NOT in regular validation output* [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-ShowValidatorInternalTimes)"
            allowExampleUrls:
              type: boolean
              description: "Turns off errors produced by examples in the FHIR specification with URLs referring to `example.org`. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-ExampleURLs)"
            txServer:
              type: string
              description: "The terminology server url. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-TerminologyServer)"
            snomedCT:
              type: string
              enum:
                - intl
                - us
                - uk
                - es
                - nl
                - ca
                - dk
                - se
                - au
                - be
              description: "The edition of SNOMED CT used when the terminology server does SNOMED CT validation. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-SNOMEDCT)"
            sv:
              type: string
              enum:
                - 1.0.2
                - 1.4.0
                - 3.0.2
                - 4.1.0
                - 4.3.0
                - 5.0
                - 5.0.0
              description: "Base FHIR version for validation. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Choosingtheversion)"
            igs:
              type: array
              items:
                type: string
              description: "A list of published implementation guides to validate against. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Validatingagainstanimplementationguide)"
            locale:
              type: string
              enum:
                - en
                - de
                - es
              description: "Specified the locale/language of the validation result messages. [[more...]](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Locale)"
          example:
            sv: "4.0.1"
            ig: [ "hl7.fhir.us.core#4.0.0" ]
            locale: "en"
        filesToValidate:
          type: array
          items:
            properties:
              fileName:
                type: string
                example: "manually_entered_file.json"
              fileContent:
                type: string
                example: "{\"resourceType\": \"Patient\"}"
              fileType:
                type: string
                example: "json"
        sessionId:
          type: string
          example: "32fc25cf-020e-4492-ace5-03fe904d22e0"
          description: "The unique server-generated ID of an existing validation session. If this field is not present, a serverId will be generated by the server and returned in the ValidationResponse."
      required:
        - cliContext
        - filesToValidate
        - sessionId
    validateResponse:
      type: object
      properties:
        outcomes:
          type: array
          items:
            properties:
              fileInfo:
                type: array
                items:
                  properties:
                    fileName:
                      type: string
                      example: "manually_entered_file.json"
                    fileContent:
                      type: string
                      example: "{\n  \"resourceType\": \"Patient\"}"
                    fileType:
                      type: string
                      example: "json"
              issues:
                type: array
                example: []
        sessionId:
          type: string
          example: "32fc25cf-020e-4492-ace5-03fe904d22e0"
          description: "The unique server-generated ID of the validation session that produced this validation response. Once instantiated, a session maintains loaded IGs and other FHIR resources in memory to speed up subsequent validations. Sessions persist for an hour and are then removed."
    listIgsResponse:
      type: object
      properties:
        packageInfo:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              version:
                type: string
              fhirVersion:
                type: string
              url:
                type: string
          example:
            - id: "hl7.fhir.us.core"
              version: "5.0.1"
              fhirVersion: "4.0.1"
              url: "http://hl7.org/fhir/us/core/STU5.0.1"
            - id: "hl7.fhir.au.base"
              version: "1.0.1"
              fhirVersion: "3.0.1"
              url: "http://hl7.org.au/fhir/base/2019Feb"
            - id: "hl7.fhir.us.davinci-pcde"
              version: null
              fhirVersion: null
              url: null
    listIgVersionsResponse:
      type: object
      properties:
        packageInfo:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              version:
                type: string
              fhirVersion:
                type: string
              url:
                type: string
          example:
            - id: "hl7.fhir.us.core"
              version: "0.0.0"
              fhirVersion: "STU3"
              url: "https://packages.simplifier.net/hl7.fhir.us.core/0.0.0"
            - id: "hl7.fhir.us.core"
              version: "1.0.0"
              fhirVersion: "STU3"
              url: "https://packages.simplifier.net/hl7.fhir.us.core/1.0.0"
            - id: "hl7.fhir.us.core"
              version: "5.0.1"
              fhirVersion: "R4"
              url: "https://packages.simplifier.net/hl7.fhir.us.core/5.0.1"
    listSupportedFhirVersions:
      type: object
      properties:
        versions:
          type: array
          items:
            type: string
          example:
            - "1.0.2"
            - "1.4.0"
            - "3.0.2"
            - "4.0.1"
            - "4.1.0"
            - "4.3.0"
            - "5.0"
            - "4.6.0"
    validateTerminologyServerRequest:
      type: object
      properties:
        url:
          type: string
          example: "http://tx.fhir.org/r4"
    validateTerminologyServerResponse:
      type: object
      properties:
        url:
          type: string
          example: "http://tx.fhir.org/r4"
        validTxServer:
          type: boolean
          example: true
        details:
          type: string
          example: ""
    terminologyServerStatus:
      type: boolean
      example: true
    packageServerStatus:
      type: boolean
      example: true

